

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jesus Vazquez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        panelVenta = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        titleDashboard = new javax.swing.JLabel();
        btnSupplier = new javax.swing.JLabel();
        btnShop = new javax.swing.JLabel();
        btnInventory = new javax.swing.JLabel();
        btnShopping = new javax.swing.JLabel();
        btnShopping1 = new javax.swing.JLabel();
        panelSlide = new javax.swing.JPanel();
        panelSale = new javax.swing.JPanel();
        titleSale = new javax.swing.JLabel();
        lblQuantityShop = new javax.swing.JLabel();
        comboQuantity = new javax.swing.JComboBox<>();
        lblNameShop = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        scrollSale = new javax.swing.JScrollPane();
        tableSale = new javax.swing.JTable();
        btnBuy = new java.awt.Label();
        panelInventory = new javax.swing.JPanel();
        titleInventory = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        lblSuplier = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblQuantityInv = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        ScrollInventory = new javax.swing.JScrollPane();
        tableInventory = new javax.swing.JTable();
        btnModify = new java.awt.Label();
        txtAddInv = new java.awt.Label();
        btnDelete = new java.awt.Label();
        comboSize = new javax.swing.JComboBox<>();
        comboSupplier = new javax.swing.JComboBox<>();
        lblQuantityInv1 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        panelSupplier = new javax.swing.JPanel();
        titleSupplier = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnAddSupplier = new java.awt.Label();
        scrollSupplier = new javax.swing.JScrollPane();
        tableSupplier = new javax.swing.JTable();
        panelShopping = new javax.swing.JPanel();
        titleInventory1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelUser = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVenta.setBackground(new java.awt.Color(0, 0, 0));
        panelVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(0, 51, 51));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleDashboard.setBackground(new java.awt.Color(255, 255, 255));
        titleDashboard.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        titleDashboard.setForeground(new java.awt.Color(204, 204, 204));
        titleDashboard.setText("Dashboard");
        panelMenu.add(titleDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnSupplier.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplier.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_supplier.png"))); // NOI18N
        btnSupplier.setText("Supplier");
        btnSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierMouseClicked(evt);
            }
        });
        panelMenu.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 30));

        btnShop.setBackground(new java.awt.Color(255, 255, 255));
        btnShop.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnShop.setForeground(new java.awt.Color(255, 255, 255));
        btnShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_shopping.png"))); // NOI18N
        btnShop.setText("Sale");
        btnShop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShopMouseClicked(evt);
            }
        });
        panelMenu.add(btnShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        btnInventory.setBackground(new java.awt.Color(255, 255, 255));
        btnInventory.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_inventory.png"))); // NOI18N
        btnInventory.setText("Inventory");
        btnInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventoryMouseClicked(evt);
            }
        });
        panelMenu.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 30));

        btnShopping.setBackground(new java.awt.Color(255, 255, 255));
        btnShopping.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnShopping.setForeground(new java.awt.Color(255, 255, 255));
        btnShopping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_white.png"))); // NOI18N
        btnShopping.setText("User");
        btnShopping.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShopping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShoppingMouseClicked(evt);
            }
        });
        panelMenu.add(btnShopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 40));

        btnShopping1.setBackground(new java.awt.Color(255, 255, 255));
        btnShopping1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnShopping1.setForeground(new java.awt.Color(255, 255, 255));
        btnShopping1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgShop.png"))); // NOI18N
        btnShopping1.setText("Shopping");
        btnShopping1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShopping1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShopping1MouseClicked(evt);
            }
        });
        panelMenu.add(btnShopping1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 30));

        panelVenta.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 480));

        panelSlide.setLayout(new java.awt.CardLayout());

        panelSale.setBackground(new java.awt.Color(0, 0, 0));
        panelSale.setForeground(new java.awt.Color(255, 255, 255));
        panelSale.setInheritsPopupMenu(true);
        panelSale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleSale.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        titleSale.setForeground(new java.awt.Color(204, 204, 204));
        titleSale.setText("Sale control");
        panelSale.add(titleSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblQuantityShop.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblQuantityShop.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantityShop.setText("Quantity");
        panelSale.add(lblQuantityShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        comboQuantity.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        comboQuantity.setBorder(null);
        panelSale.add(comboQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 30));

        lblNameShop.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblNameShop.setForeground(new java.awt.Color(255, 255, 255));
        lblNameShop.setText("Name");
        panelSale.add(lblNameShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        comboProducto.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        comboProducto.setBorder(null);
        panelSale.add(comboProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 460, 30));

        tableSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Description", "Quantity", "Total"
            }
        ));
        scrollSale.setViewportView(tableSale);
        if (tableSale.getColumnModel().getColumnCount() > 0) {
            tableSale.getColumnModel().getColumn(0).setResizable(false);
            tableSale.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        panelSale.add(scrollSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 590, 250));

        btnBuy.setAlignment(java.awt.Label.CENTER);
        btnBuy.setBackground(new java.awt.Color(0, 153, 102));
        btnBuy.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy.setText("Buy now");
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuyMouseClicked(evt);
            }
        });
        panelSale.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 130, 40));

        panelSlide.add(panelSale, "card4");

        panelInventory.setBackground(new java.awt.Color(0, 0, 0));
        panelInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleInventory.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        titleInventory.setForeground(new java.awt.Color(255, 255, 255));
        titleInventory.setText("Inventory");
        panelInventory.add(titleInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        lblName.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Code");
        panelInventory.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtCode.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelInventory.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 180, 30));

        lblBrand.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(255, 255, 255));
        lblBrand.setText("Brand");
        panelInventory.add(lblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtBrand.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelInventory.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, 30));

        txtDescription.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelInventory.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 180, 30));

        lblDescription.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Description");
        panelInventory.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        lblSuplier.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblSuplier.setForeground(new java.awt.Color(255, 255, 255));
        lblSuplier.setText("Supplier");
        panelInventory.add(lblSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        txtQuantity.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelInventory.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 60, 30));

        lblQuantityInv.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblQuantityInv.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantityInv.setText("Quantity");
        panelInventory.add(lblQuantityInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblSize.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblSize.setForeground(new java.awt.Color(255, 255, 255));
        lblSize.setText("Size");
        panelInventory.add(lblSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        tableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Brand", "Quantity", "Descripcion", "Supplier", "Size", "Cost"
            }
        ));
        ScrollInventory.setViewportView(tableInventory);

        panelInventory.add(ScrollInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 300, 620, 160));

        btnModify.setAlignment(java.awt.Label.CENTER);
        btnModify.setBackground(new java.awt.Color(153, 0, 255));
        btnModify.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnModify.setText("Modify");
        panelInventory.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 130, 40));

        txtAddInv.setAlignment(java.awt.Label.CENTER);
        txtAddInv.setBackground(new java.awt.Color(0, 153, 51));
        txtAddInv.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtAddInv.setText("Add");
        txtAddInv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddInvMouseClicked(evt);
            }
        });
        panelInventory.add(txtAddInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 130, 40));

        btnDelete.setAlignment(java.awt.Label.CENTER);
        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        panelInventory.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 130, 40));

        comboSize.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelInventory.add(comboSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 110, 30));

        comboSupplier.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        comboSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike S.A de C.V", "Adidas S.A de C.V" }));
        comboSupplier.setSelectedIndex(-1);
        panelInventory.add(comboSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 180, 30));

        lblQuantityInv1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblQuantityInv1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantityInv1.setText("Cost:");
        panelInventory.add(lblQuantityInv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 30));

        txtCosto.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelInventory.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, 30));

        panelSlide.add(panelInventory, "card3");

        panelSupplier.setBackground(new java.awt.Color(0, 0, 0));
        panelSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleSupplier.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        titleSupplier.setForeground(new java.awt.Color(255, 255, 255));
        titleSupplier.setText("Supplier");
        panelSupplier.add(titleSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        lblRfc.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblRfc.setForeground(new java.awt.Color(255, 255, 255));
        lblRfc.setText("RFC");
        panelSupplier.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblCompany.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(255, 255, 255));
        lblCompany.setText("Company");
        panelSupplier.add(lblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        txtCompany.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });
        panelSupplier.add(txtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 190, 30));

        txtRfc.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        panelSupplier.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, 30));

        lblAddress.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address");
        panelSupplier.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        txtAddress.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelSupplier.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 190, 30));

        lblPhone.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("Phone");
        panelSupplier.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtPhone.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        panelSupplier.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, 30));

        btnAddSupplier.setAlignment(java.awt.Label.CENTER);
        btnAddSupplier.setBackground(new java.awt.Color(0, 153, 51));
        btnAddSupplier.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        btnAddSupplier.setText("Add");
        btnAddSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSupplierMouseClicked(evt);
            }
        });
        panelSupplier.add(btnAddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 40));

        tableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RFC", "Phone", "Company", "Address"
            }
        ));
        scrollSupplier.setViewportView(tableSupplier);

        panelSupplier.add(scrollSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 580, 260));

        panelSlide.add(panelSupplier, "card2");

        panelShopping.setBackground(new java.awt.Color(0, 0, 0));
        panelShopping.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleInventory1.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        titleInventory1.setForeground(new java.awt.Color(255, 255, 255));
        titleInventory1.setText("Shopping");
        panelShopping.add(titleInventory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IdProducto", "Provedor", "Total", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelShopping.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 400));

        panelSlide.add(panelShopping, "card5");

        panelUser.setBackground(new java.awt.Color(0, 0, 0));
        panelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Correo", "Telefono", "Rol"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        panelUser.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 570, 380));

        panelSlide.add(panelUser, "card6");

        panelVenta.add(panelSlide, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 660, 490));

        getContentPane().add(panelVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void btnShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShopMouseClicked
      panelSale.setVisible(true);
      panelInventory.setVisible(false);
      panelSupplier.setVisible(false);
      panelShopping.setVisible(false);
    }//GEN-LAST:event_btnShopMouseClicked

    private void btnInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventoryMouseClicked
      panelSale.setVisible(false);
      panelInventory.setVisible(true);
      panelSupplier.setVisible(false);
      panelShopping.setVisible(false);
    }//GEN-LAST:event_btnInventoryMouseClicked

    private void btnSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMouseClicked
      panelSale.setVisible(false);
      panelInventory.setVisible(false);
      panelSupplier.setVisible(true);
      panelShopping.setVisible(false);
    }//GEN-LAST:event_btnSupplierMouseClicked

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcActionPerformed

    private void btnAddSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSupplierMouseClicked
        validaciones validar = new validaciones();
        boolean rfc = validar.valRfc(txtRfc.getText().toString());
        boolean phone = validar.valNumbers(txtPhone.getText().toString());
        boolean nameCompany = validar.valCompany(txtCompany.getText().toString());
        boolean address = validar.valAddress(txtAddress.getText().toString());
        //valida el rcf
        if(rfc){
            JOptionPane.showMessageDialog(null, "RFC VALIDO");
            //valida el telefono
            if(phone){
                JOptionPane.showMessageDialog(null, "TELEFONO VALIDO");
                if(nameCompany){
                    JOptionPane.showMessageDialog(null, "RAZON S. VALIDO");
                    if(address){
                        JOptionPane.showMessageDialog(null, "DIRECCION VALIDO");
                    }else{
                        JOptionPane.showMessageDialog(null, "DIRECCION INVALIDO");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "RAZON S. INVALIDO");
                }
            }else{
                JOptionPane.showMessageDialog(null, "TELEFONO INVALIDO");
            }
        }else{
            JOptionPane.showMessageDialog(null, "RFC INVALIDO");
        }
        
    }//GEN-LAST:event_btnAddSupplierMouseClicked

    private void txtAddInvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddInvMouseClicked
        validaciones vali = new validaciones();
        boolean nombreProducto = vali.valCodigo(txtCode.getText().toString());
        boolean marca = vali.valName(txtBrand.getText().toString());
        boolean cantidad = vali.numers(txtQuantity.getText().toString());
        boolean descripcion = vali.valName(txtDescription.getText().toString());
        if(nombreProducto){
            JOptionPane.showMessageDialog(null, "NOMBRE VALIDO");
            if(marca){
                JOptionPane.showMessageDialog(null, "MARCA VALIDO");
                if(cantidad){
                    JOptionPane.showMessageDialog(null, "CANTIDAD VALIDO");
                    if(descripcion){
                        JOptionPane.showMessageDialog(null, "DESCRIPCION VALIDO");
                    }else{
                        JOptionPane.showMessageDialog(null, "DESCRIPCION INVALIDO");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "CANTIDAD INVALIDO");
                }
            }else{
                JOptionPane.showMessageDialog(null, "MARCA INVALIDO");
            }
        }else{
            JOptionPane.showMessageDialog(null, "NOMBRE INVALIDO");
        }
    }//GEN-LAST:event_txtAddInvMouseClicked

    private void btnShoppingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShoppingMouseClicked
        panelSale.setVisible(false);
        panelInventory.setVisible(false);
        panelSupplier.setVisible(false);
        panelShopping.setVisible(true);
    }//GEN-LAST:event_btnShoppingMouseClicked

    private void btnBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseClicked
        
        
    }//GEN-LAST:event_btnBuyMouseClicked

    private void btnShopping1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShopping1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShopping1MouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollInventory;
    private java.awt.Label btnAddSupplier;
    private java.awt.Label btnBuy;
    private java.awt.Label btnDelete;
    private javax.swing.JLabel btnInventory;
    private java.awt.Label btnModify;
    private javax.swing.JLabel btnShop;
    private javax.swing.JLabel btnShopping;
    private javax.swing.JLabel btnShopping1;
    private javax.swing.JLabel btnSupplier;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JComboBox<String> comboQuantity;
    private javax.swing.JComboBox<String> comboSize;
    private javax.swing.JComboBox<String> comboSupplier;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameShop;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQuantityInv;
    private javax.swing.JLabel lblQuantityInv1;
    private javax.swing.JLabel lblQuantityShop;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSuplier;
    private javax.swing.JPanel panelInventory;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSale;
    private javax.swing.JPanel panelShopping;
    private javax.swing.JPanel panelSlide;
    private javax.swing.JPanel panelSupplier;
    private javax.swing.JPanel panelUser;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JScrollPane scrollSale;
    private javax.swing.JScrollPane scrollSupplier;
    private javax.swing.JTable tableInventory;
    private javax.swing.JTable tableSale;
    private javax.swing.JTable tableSupplier;
    private javax.swing.JLabel titleDashboard;
    private javax.swing.JLabel titleInventory;
    private javax.swing.JLabel titleInventory1;
    private javax.swing.JLabel titleSale;
    private javax.swing.JLabel titleSupplier;
    private java.awt.Label txtAddInv;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
